### ISSUE TITLE
Implement correct "required" field indiactor

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-commons#24]
Today the way we use the "Required" field indicator is inconsistent in Certification and other places. Here is the specific guidance. We should make this consistent across our apps.

*Note that we should not colons after questions which means we probably need to edit the question labels in Certification to accommodate this.*

![image](https://cloud.githubusercontent.com/assets/6335546/21364915/ea7683a6-c6c0-11e6-99f4-4afb49d71de8.png)

- [x] For boxes, right align "Required" label
- [x] Don't add parentheses around "Required" label (for checkbox/radio questions)
- [x] Keep at least 2px spacing b/t "Required" label and text to the left (for checkbox/radio questions)
- [x] Left align "required" label (for checkbox/radio questions)
- [x] Don't use colons at the end of questions or labels

**Comment by slj** [comment]
Please note 8B in the attached GIF:

![form9respissues](https://cloud.githubusercontent.com/assets/1053255/22664899/9f381b4e-ec80-11e6-90bf-c9cd4d29dad9.gif)

the Style Guide does not recommend how to indent when the label spans 2+ lines.  Also, the inline radios buttons sit directly on top each other.  IMO we keep the margin on the bottom of the inline radios - this will, at least in Form 9, keep the buttons apart and make vertical spacing from the next question consistent with non-inline radios.  As for the label text I wouldn't bother indenting lines 2+, because there's no one-indention-size-fits-all (well...with FlexBox this is easy to do but IE9 doesn't support it, so we'd need a polyfill).

@KHarshawat, @mmlumba, @Chingujo any thoughts?

**Comment by slj** [comment]
@KHarshawat @KHarshawat-gov do we really need to left-align the "Required" label (point 4)?

**Comment by slj** [comment]
Didn't notice anywhere in `efolder` where labels need ":" removed.

**Comment by slj** [comment]
Looks like someone's previous commit handled points 1, 2 and 5.

**Comment by KHarshawat-gov** [comment]
Awesome :) LMK if you still need feedback...

**Comment by kierachell** [comment]
Works on **Certification**:
<img width="630" alt="screen shot 2017-02-08 at 20 05 16" src="https://cloud.githubusercontent.com/assets/18075411/22764672/1225594a-ee3a-11e6-91a4-bae7fc3ad3ef.png">
<img width="394" alt="screen shot 2017-02-08 at 20 05 43" src="https://cloud.githubusercontent.com/assets/18075411/22764673/122742d2-ee3a-11e6-88ba-07089accc4b9.png">
<img width="566" alt="screen shot 2017-02-08 at 20 16 35" src="https://cloud.githubusercontent.com/assets/18075411/22764926/8cc1d218-ee3b-11e6-858f-95d7575620b9.png">



**Feedback** needs update from @KHarshawat for acceptance criteria:
PII warning has moved along with _Required_ text.
<img width="631" alt="screen shot 2017-02-08 at 20 13 25" src="https://cloud.githubusercontent.com/assets/18075411/22764840/229808da-ee3b-11e6-8daa-726223bf58ed.png">



------------
Note, this is tested on `dev`, the Gemfiles on caseflow, caseflow-efolder, and caseflow-feedback will need to be updated for the latest version to deploy this change.
```
gem "caseflow", git: "https://github.com/department-of-veterans-affairs/caseflow-commons", ref: "fa1b297"
```
